
INSERT INTO users (name, email, password, phone_number, address, picture_url, bio)
VALUES 
('Betsy', 'moo@moo.com', 'moo', '+17807806969', 'Everywhere You Need St.', 'https://external-content.duckduckgo.com/iu/?u=http%3A%2F%2Fimg15.deviantart.net%2F0b3c%2Fi%2F2013%2F237%2F5%2F3%2Fbetsy_the_cow____bought__by_alonegothictomboy-d6jpxza.png&f=1&nofb=1', 'My name is Betsy and I kind of run things here at better place, I make it a better place just by existing amongst you fucking peasant mortals, you should appreciate being close to me because you get some of my regurgitated air.'),
('Cecil Vogrinetz', 'c.vogrinetz@better-place.com', 'password', '+17807807800', '4111 Earles St, Vancouver', 'https://i.pravatar.cc/300', 'Hi, my name is Cecil, I love to throw on a pair of loose panties and watch days of our lives... days of our lives is what really gets my rocks off after a hard day of eating dorritos and playing with computers.'),
('Mitchel Sarauer', 'oldMan@oldmen.com', 'password', '+12342342345', 'Colonial St NE', 'https://i.pravatar.cc/301', 'My name is mitch I love long walks on the beach, as long as they are 50 feet from any school, I am a registered sex offender... I got into trouble a couple months ago and ended up on dateline nbc, Chris Hansen is a real prick.'),
('Logan Thomas', 'logannormanthomas@protonmail.com', 'password', '+17805170260', '4999 Earles St, Vancouver', 'https://i.pravatar.cc/302', 'A canadian web developer looking to do his part, I feel like this site enables me to help people on an individual level which is really important to me.'),
('Bob Loblaw', 'b0bl0ba3@hotmail.com', 'password', '+17804729234', '777 Imagination Avenue, Vancouver', 'https://i.pravatar.cc/303', 'I am eager to help fellow members of my community. I think giving back is an important part or goal in life.'),
('Sally Rayburn', 'sally_r@hotmail.com', 'password', '+17802345276', '68812 Baker Ave, Cochrane', 'https://i.pravatar.cc/303', 'I cannot wait to meet some like minded people, I really think I can make a difference. PS... I love to cook so if you have any baking needs let me know :)'),
('Kevin Scherger', 'luckynumber_7777@msn.com', 'password', '+17804523425', '11232 Seymore St, Calgary', 'https://i.pravatar.cc/303', 'Hi, my name is Kevin, I really like making people smile, I just recently signed up for better world and I hope I can help do exactly that: do my part and make the world a better place.'),
('Cindy Windshire', 'snippysass@gmail.com', 'password', '+17802345787', '95556 Bernard Ave, Vancouver', 'https://i.pravatar.cc/303', 'Cindy Windshire is the name and volunteering is my game. I really like how better place is taking a different spin on volunteering. I just signed up and am EXCITED!'),
('Sarah Samson', 'sara_forever_21@protonmail.com', 'password', '+17808447867', 'Sally St NW, Edmonton', 'https://i.pravatar.cc/303', 'I do not know where to start! I love helping people, when I am not at the hospital working as a nurse you can see me helping out at the homeless shelter!'),
('Johnny Zelewski', 'kingj0nath0n@gmail.com', 'password', '+17806789989', '78567 Patterson Avenue, Kelowna', 'https://i.pravatar.cc/303', 'Hoping to meet some like minded people here, here to help and make the world a better place.'),

-- Cochrane
('Johnny Sesame', 'jSesam3@hotmail.com', 'password', '+17807806969', '88996 Eagle Avenue, Cochrane', 'https://i.pravatar.cc/302', 'Hi, people call me by my last name Sesame, and I am really excited to get out there and put myself to work helping other people.'),
('Sam Seget', 'seget23@gmail.com', 'password', '+17807807800', '2323 Hope St, Cochrane', 'https://i.pravatar.cc/300', 'My name is Seget and I love to play the guitar and plan things, I am also excited to get out of my shell and meet new people that are kind hearted and want to help people like I do.'),
('Christina Bulmer', 'cBulmer@protonmail.com', 'password', '+12342342345', '766 Coleman St NW, Calgary', 'https://i.pravatar.cc/301', 'I cannot wait to start helping people, better place is a dream, I am excited to help people on an individual basis, this style of volunteering feels so much more rewarding.'),
('Nicole Hitchcock', 'hitch999@msn.com', 'password', '+17805170260', '3993 Macintosh Ave, Cochrane', 'https://i.pravatar.cc/302', 'Hi, my name is Nicole, I have a ton of hobbies, and I am hoping through better place I can pick up another one, helping people :)'),
('Megan T', 'the_m_team@protonmail.com', 'password', '+17804729234', '90912 Swanson Ave, Calgary', 'https://i.pravatar.cc/303', 'I am eager to help fellow members of my community. I think giving back is an important part or goal in life.'),
('Sally Rayburn', 'sally_r@hotmail.com', 'password', '+17802345276', '68812 Baker Ave, Cochrane', 'https://i.pravatar.cc/303', 'I cannot wait to meet some like minded people, I really think I can make a difference. PS... I love to cook so if you have any baking needs let me know :)'),
('Kevin Scherger', 'luckynumber_7777@msn.com', 'password', '+17804523425', '11232 Seymore St, Calgary', 'https://i.pravatar.cc/303', 'Hi, my name is Kevin, I really like making people smile, I just recently signed up for better world and I hope I can help do exactly that: do my part and make the world a better place.'),
('Cindy Windshire', 'snippysass@gmail.com', 'password', '+17802345787', '95556 Bernard Ave, Vancouver', 'https://i.pravatar.cc/303', 'Cindy Windshire is the name and volunteering is my game. I really like how better place is taking a different spin on volunteering. I just signed up and am EXCITED!'),
('Sarah Samson', 'sara_forever_21@protonmail.com', 'password', '+17808447867', 'Sally St NW, Edmonton', 'https://i.pravatar.cc/303', 'I do not know where to start! I love helping people, when I am not at the hospital working as a nurse you can see me helping out at the homeless shelter!'),
('Johnny Zelewski', 'kingj0nath0n@gmail.com', 'password', '+17806789989', '78567 Patterson Avenue, Kelowna', 'https://i.pravatar.cc/303', 'Hoping to meet some like minded people here, here to help and make the world a better place.')