
INSERT INTO users (name, email, password, phone_number, address, picture_url, bio)
VALUES 
('Betsy', 'moo@moo.com', 'moo', '+17807806969', 'Everywhere You Need St.', 'http://cdn.iflscience.com/images/2210d5e6-5f21-59cb-8b58-664d42a0b1e3/content-1497609145-blue-moo.jpg', 'My name is Betsy and I kind of run things here at better place, I make it a better place just by existing amongst you fucking peasant mortals, you should appreciate being close to me because you get some of my regurgitated air.'),
('Cecil Vogrinetz', 'cv@cv.com', 'cv', '+17807807800', '4111 Earles St, Vancouver', 'https://www.denofgeek.com/wp-content/uploads/2019/10/header_main_image_2.jpg?resize=768%2C432', 'Hi, my name is Cecil, I love to throw on a pair of loose panties and watch days of our lives... days of our lives is what really gets my rocks off after a hard day of eating dorritos and playing with computers.'),
('Mitchel Sarauer', 'oldMan@oldmen.com', 'password', '+12342342345', 'Colonial St NE', 'https://i.redd.it/w6yto6fnfvl21.jpg', 'My name is mitch I love long walks on the beach, as long as they are 50 feet from any school, I am a registered sex offender... I got into trouble a couple months ago and ended up on dateline nbc, Chris Hansen is a real prick.'),
('Logan Thomas', 'logannormanthomas@protonmail.com', 'password', '+17805170260', '4999 Earles St, Vancouver', 'https://media-exp3.licdn.com/dms/image/C4E03AQGXQUlLiq7jsw/profile-displayphoto-shrink_200_200/0/1623715263460?e=1631750400&v=beta&t=E7u5vwmTFOY_ukTlzefqcfG3o212lEEfIiG6zg8LQ1U', 'A canadian web developer looking to do his part, I feel like this site enables me to help people on an individual level which is really important to me.'),
('Frodo Baggins', 'ringbeaer@ring.com', 'cv', '+17807807800', '4111 Earles St, Vancouver', 'https://i.ytimg.com/vi/T-COPuWD-Qw/maxresdefault.jpg', 'Hi, my name is Cecil, I love to throw on a pair of loose panties and watch days of our lives... days of our lives is what really gets my rocks off after a hard day of eating dorritos and playing with computers.'),
('Samwise Gamgee', 'b0bl0ba3@hotmail.com', 'password', '+17804729234', '777 Imagination Avenue, Vancouver', 'https://yt3.ggpht.com/ytc/AKedOLTLLrr8Etc4OtrPYa61wvC-gO7Jlb9Pc_B3sRCy=s900-c-k-c0x00ffffff-no-rj', 'I am eager to help fellow members of my community. I think giving back is an important part or goal in life.'),
('Sally Rayburn', 'sally_r@hotmail.com', 'password', '+17802345276', '68812 Baker Ave, Cochrane', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.8GjYi6k-6fdYp-Orlh1NVAAAAA%26pid%3DApi&f=1', 'I cannot wait to meet some like minded people, I really think I can make a difference. PS... I love to cook so if you have any baking needs let me know :)'),
('Tobey Maguire', 't_maguire_7777@msn.com', 'password', '+17804523425', '11232 Seymore St, Calgary', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.7m86aqwtby3AUWDWd_AZMwHaDI%26pid%3DApi&f=1', 'Hi, my name is Kevin, I really like making people smile, I just recently signed up for better world and I hope I can help do exactly that: do my part and make the world a better place.'),
('Gandalf', 'snippysass@gmail.com', 'password', '+17802345787', '95556 Bernard Ave, Vancouver', 'https://optimistminds.com/wp-content/uploads/Gandalf-quotes.jpg', 'Cindy Windshire is the name and volunteering is my game. I really like how better place is taking a different spin on volunteering. I just signed up and am EXCITED!'),
('Smeagol (Gollum)', 'my_precious@protonmail.com', 'password', '+17808447867', 'Sally St NW, Edmonton', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Fmedia.giphy.com%2Fmedia%2F12Pb87uq0Vwq2c%2Fgiphy.gif&f=1&nofb=1', 'I do not know where to start! I love helping people, when I am not at the hospital working as a nurse you can see me helping out at the homeless shelter!'),
('Andy Lindsay', 'andyLindsay@PyCar.com', 'password', '+17806789989', '78567 Patterson Avenue, Vancouver', 'https://ca.slack-edge.com/T2G8TE2E5-UDC0C5605-7147c37e77b3-72', 'I am just on here because I am worried about PyCar.'),

-- Cochrane
('Johnny Sesame', 'jSesam3@hotmail.com', 'password', '+17807806969', '88996 Eagle Avenue, Cochrane', 'https://i.pravatar.cc/302', 'Hi, people call me by my last name Sesame, and I am really excited to get out there and put myself to work helping other people.'),
('Sam Seget', 'seget23@gmail.com', 'password', '+17807807800', '2323 Hope St, Cochrane', 'https://i.pravatar.cc/300', 'My name is Seget and I love to play the guitar and plan things, I am also excited to get out of my shell and meet new people that are kind hearted and want to help people like I do.'),
('Christina Bulmer', 'cBulmer@protonmail.com', 'password', '+12342342345', '766 Coleman St NW, Calgary', 'https://i.pravatar.cc/301', 'I cannot wait to start helping people, better place is a dream, I am excited to help people on an individual basis, this style of volunteering feels so much more rewarding.'),
('Nicole Hitchcock', 'hitch999@msn.com', 'password', '+17805170260', '3993 Macintosh Ave, Cochrane', 'https://i.pravatar.cc/302', 'Hi, my name is Nicole, I have a ton of hobbies, and I am hoping through better place I can pick up another one, helping people :)'),
('Megan T', 'the_m_team@protonmail.com', 'password', '+17804729234', '90912 Swanson Ave, Calgary', 'https://i.pravatar.cc/303', 'I am eager to help fellow members of my community. I think giving back is an important part or goal in life.'),
('Sally Rayburn', 'sally_r@hotmail.com', 'password', '+17802345276', '68812 Baker Ave, Cochrane', 'https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.8GjYi6k-6fdYp-Orlh1NVAAAAA%26pid%3DApi&f=1', 'I cannot wait to meet some like minded people, I really think I can make a difference. PS... I love to cook so if you have any baking needs let me know :)'),
('Kevin Scherger', 'luckynumber_7777@msn.com', 'password', '+17804523425', '11232 Seymore St, Calgary', 'https://i.pravatar.cc/303', 'Hi, my name is Kevin, I really like making people smile, I just recently signed up for better world and I hope I can help do exactly that: do my part and make the world a better place.'),
('Cindy Windshire', 'snippysass@gmail.com', 'password', '+17802345787', '95556 Bernard Ave, Vancouver', 'https://i.pravatar.cc/303', 'Cindy Windshire is the name and volunteering is my game. I really like how better place is taking a different spin on volunteering. I just signed up and am EXCITED!'),
('Sarah Samson', 'sara_forever_21@protonmail.com', 'password', '+17808447867', 'Sally St NW, Edmonton', 'https://i.pravatar.cc/303', 'I do not know where to start! I love helping people, when I am not at the hospital working as a nurse you can see me helping out at the homeless shelter!'),
('Herald Gerbaldi', 'herryG0n@gmail.com', 'password', '+17806789989', '32552 Token Ave, Cochrane', 'https://i.pravatar.cc/303', 'I am overjoyed to be a part of this network of caring people, lets make the world a better place!')